### ISSUE TITLE
it wont uninstall

### ISSUE THREAD

**Issue by starsetDragon** [markheath/skypevoicechanger#1]
ok sooo I downloaded this to have some fun with my friends but it ended up never working and honestly I had forgotten I had it for a long ass time, but I have tried to uninstall this like 5 times already and nothing happens

**Comment by markheath** [comment]
what do you mean by uninstall? how did you install it in the first place? If skypevoicechanger isn't running it will have no effect

**Comment by starsetDragon** [comment]
to uninstall it meaning to remove from my laptop, and well i found the old website at some point(I think it was like 2016-2017 I downloaded it ) i believe I downloaded it from there and once it downloaded I was never able to get it to run I never even saw the interface that you show on the overview.

**Comment by markheath** [comment]
If you downloaded binaries, then just delete them.
If you installed with ClickOnce, it can be uninstalled from Add/Remove programs

**Comment by starsetDragon** [comment]
ok well the thing is it shows up in my programs to uninstall them but it can not find it anywhere else, id thought I would add that, but ill try a program like that. can you recommend one that you like or something?

**Comment by starsetDragon** [comment]
pardon my stupidity, my mind mixed up something and thought you were talking about something else with the add/remove programs, but I have tried that and it won't work

**Comment by markheath** [comment]
in what way doesn't it work? do you get an error message?

**Comment by starsetDragon** [comment]
nothing displayed, nor popped up, nothing happens otherwise I probably would have figured it out myself. it just never worked. do you think I should try installing it again and then see if I can uninstall it?

**Comment by markheath** [comment]
Yeah maybe. It just uses ClickOnce, so the actual files will be in some weirdly named folder in your AppData folder. Where did you install it from in the first place?

**Comment by starsetDragon** [comment]
this is the site i downloaded it from https://archive.codeplex.com/?p=skypefx

**Comment by starsetDragon** [comment]
btw thank you for taking the time to helping me figure this out i really appreciate it

**Comment by markheath** [comment]
OK, so it probably was a clickonce install. Codeplex has shut down since you installed it, so I wonder if its trying to call home as part of the uninstall and not finding anything. 

You could try some of the ideas mentioned here - https://stackoverflow.com/a/10915212/7532

**Comment by starsetDragon** [comment]
ok thank you so much, im read all of this and maybe try installing it again if all else fails anywho il try not to bother you anymore thank you ^-^

**Comment by starsetDragon** [comment]
it worked thank you so much ^-^hope your day goes wonderfully well ^-^

**Comment by markheath** [comment]
great, glad you got it sorted
