### ISSUE TITLE
No DNF file available for Fedora 

### ISSUE THREAD

**Issue by jmayekar** [markheath/skypevoicechanger#2]
I wanted dnf file to install on fedora machine. 

Is there any way 

Thanks and best,
J M

**Comment by markheath** [comment]
Sorry, this is a windows only project

**Comment by jmayekar** [comment]
Hi Mark,

Thanks but i was thinking if any developer who can be called on  or simply float on fedora forum. Someone will take initiative to work here

Thanks,
jay
________________________________
